cask_args appdir: '/Applications'

tap 'homebrew/bundle'
tap 'homebrew/core'
tap 'caskroom/cask'
tap 'caskroom/versions'

brew 'git'
brew 'git-flow-avh'
brew 'imagemagick'
brew 'node'
brew 'npm'
brew 'nvm'
brew 'ssh-copy-id'
brew 'wget'
brew 'tophat/bar/yvm'
brew 'zsh'

cask '1password'
cask 'adobe-creative-cloud'
cask 'alfred'
cask 'appcleaner'
cask 'daisydisk'
cask 'dropbox'
cask 'evernote'
cask 'firefoxdeveloperedition'
cask 'postman'
cask 'sketch'
cask 'skitch'
cask 'spark'
cask 'spectacle'
cask 'spotify'
